const CONFIG={SPREADSHEET_ID:'COLE_AQUI_O_ID_DA_PLANILHA',ADMIN_SECRET:'COLE_AQUI_UM_SEGREDO_FORTE'};
function doPost(e){try{const b=JSON.parse(e.postData.contents||'{}');return json({ok:true,data:route(b)})}catch(err){return json({ok:false,error:String(err.message||err)})}}
function route(b){switch(b.action){case'setup':return setup();case'listQuestions':return listQuestions();case'register':return register(b);case'login':return login(b);case'adminListQuestions':checkAdmin(b);return rows('PERGUNTAS');case'adminCreateQuestion':checkAdmin(b);return createQuestion(b);case'adminDeleteQuestion':checkAdmin(b);return deleteQuestion(b.id);default:throw Error('Ação inválida.')}}
function ss(){return SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID)}function sh(n){return ss().getSheetByName(n)}
function setup(){[['PERGUNTAS',['id','pergunta','alternativaA','alternativaB','alternativaC','alternativaD','correta','categoria','explicacao','ativa','criadoEm']],['USUARIOS',['id','nome','email','senhaHash','criadoEm']],['RESULTADOS',['id','usuarioId','nome','categoria','pontos','total','percentual','criadoEm']]].forEach(x=>{let s=sh(x[0])||ss().insertSheet(x[0]);if(s.getLastRow()==0)s.appendRow(x[1])});return'OK'}
function rows(n){let s=sh(n);if(!s||s.getLastRow()<2)return[];let h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0],v=s.getRange(2,1,s.getLastRow()-1,s.getLastColumn()).getValues();return v.map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]])))}
function listQuestions(){return rows('PERGUNTAS').filter(q=>String(q.ativa).toUpperCase()!=='FALSE'&&String(q.ativa).toUpperCase()!=='NÃO')}
function register(b){let email=String(b.email).trim().toLowerCase();if(rows('USUARIOS').some(u=>String(u.email).toLowerCase()===email))throw Error('E-mail já cadastrado.');let id=Utilities.getUuid();sh('USUARIOS').appendRow([id,b.nome,email,sha(String(b.senha)),new Date()]);return{id,nome:b.nome,email}}
function login(b){let email=String(b.email).trim().toLowerCase(),u=rows('USUARIOS').find(x=>String(x.email).toLowerCase()===email&&String(x.senhaHash)===sha(String(b.senha)));if(!u)throw Error('E-mail ou senha incorretos.');return{user:{id:u.id,nome:u.nome,email:u.email}}}
function checkAdmin(b){if(!b.adminSecret||b.adminSecret!==CONFIG.ADMIN_SECRET||b.adminSecretEnv!==CONFIG.ADMIN_SECRET)throw Error('Acesso administrativo negado.')}
function createQuestion(b){let id=Utilities.getUuid();sh('PERGUNTAS').appendRow([id,b.pergunta,b.alternativaA,b.alternativaB,b.alternativaC,b.alternativaD,b.correta,b.categoria||'Geral',b.explicacao||'',b.ativa!==false,new Date()]);return{id}}
function deleteQuestion(id){let s=sh('PERGUNTAS'),v=s.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(id)){s.deleteRow(i+1);return'OK'}throw Error('Pergunta não encontrada.')}
function sha(t){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,t,Utilities.Charset.UTF_8).map(b=>('0'+(b&255).toString(16)).slice(-2)).join('')}
function json(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}